name: Continuous Publishing

on:
  push:
    branches:
      - production

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - run: npm ci
      - run: npm run bootstrap-ci
      - run: npm run --quiet test
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - run: npm ci
      - run: npm run bootstrap-ci
      - run: npm run build
      - run: echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
      - run: npm run publish

