name: Continuous Publishing

on:
  push:
    branches:
      - production

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - run: npm ci
      - run: npm run bootstrap-ci
      - run: npm run --quiet test
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - run: npm ci
      - run: npm run bootstrap-ci
      - run: npm run build
      - name: npm run publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

